# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171106_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_theme', models.CharField(max_length=100)),
                ('user_text', models.TextField()),
                ('message_time', models.DateTimeField()),
            ],
        ),
    ]
